### ISSUE TITLE
[Question] Is the code rollover safe?

### ISSUE THREAD

**Issue by younesmaia** [brunocalou/Timer#6]
Hello Bruno,

Congratulations on the great library! I'm using it for a personal home automation project.

Can you tell us if the code was tested for millis() rollover? How does it behaves after 9h and 32min? I haven't detected any issues so far, but my setup is not sensitive enough to detect a single timer being skipped or firing ahead of time. 
If you are already dealing with the rollover, it would be nice if you specified that in the documentation.

Also, do you have plans to release a version with a flag so the times can be specified in microseconds?

Thanks!

**Comment by brunocalou** [comment]
Hello,

Thanks for using my library 😄 
I have not tested for rollover, but reading the code, it would not work. It would stop due to this condition on Timer::update

`if(current_time - last_interval_time >= interval) {`

I think it's easy to fix, maybe something like that

`if(current_time - last_interval_time >= interval || last_interval_time < current_time) {` 

But I would have to test it

About the microseconds question, it should also be an easy feature to add. We could add a method to get time on Timer and replace all millis() calls to use this method. Then, on the constructor, we could add a parameter to specify the precision.

Or maybe change change constructor to accept a pointer to a function that gets the time, and replace the millis() calls. The default would be the millis() function, in order to keep it consistent with the current implementation.

Unfortunately, I cannot add these changes in the next weeks. I'm very busy with work, freelancing and also I'll move out next week. But I can add them after this is all over, or I could accept a Pull Request with them ;)

**Comment by younesmaia** [comment]
Oi Bruno, tudo bem?

I thought about the code for a bit and I believe it is already "rollover safe" without any modifications.
You're using unsigned long for "current_time" and "last_interval_time" variables, which is what make things work. 
When you subtract an older time from a new one using the unsigned type, you will always get the correct unsigned answer! This applies to the rollover event.

It is easier to follow If you think in bytes, instead of unsigned longs:
If the old time was 250 and you are now at 5, the difference (5 - 250), when interpreted as an unsigned byte, results in 11, which is correct.

**Comment by brunocalou** [comment]
Oi younesmaia, tudo ótimo =)

Great point, I forgot about the unsigned type. So it is safe after all, thanks for pointing it out 😄
